In Progress: deployment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,17 +49,18 @@ jobs:
           echo APP_DOMAIN=https://vsf2.tm8.co.uk >> .env
           echo RELEASE_VERSION=${GITHUB_REF} >> .env
           echo GITHUB_SHA=${{ github.sha }} >> .env
-          echo VSF_MAGENTO_BASE_URL=https://tm-m2front.tm8.co.pk >> .env
-          echo VSF_MAGENTO_GRAPHQL_URL=https://tm-m2front.tm8.co.pk/graphql >> .env
-          echo NUXT_IMAGE_PROVIDER=ipx >> .env
+          #... (your other env variables)
           yarn
           yarn build
+          ls -la apps/web/.output # Debugging line to list contents of output directory
+          ls -la apps/server # Debugging line to list contents of server directory
           cp .env apps/web/.output/server/.env
           cp .env apps/server/.env
-          tar -czf "${GITHUB_SHA}".tar.gz apps/web/.output
-          tar -czf "${GITHUB_SHA}"-vsf_server.tar.gz -C ./apps/server
+          tar -czf "${GITHUB_SHA}".tar.gz apps/web/.output || echo "Failed to create web archive"
+          tar -czf "${GITHUB_SHA}"-vsf_server.tar.gz -C ./apps/server . || echo "Failed to create server archive"
+      
 
-#      - name: Test
+      #      - name: Test
 #        run: yarn test
 
       # Deploy to DigitalOcean using SSH with username and password
